// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionsCell': string;
  'container': string;
  'emptyMessage': string;
  'monitorCell': string;
  'searchAllButton': string;
  'statusHasFile': string;
  'statusMissing': string;
}
export const cssExports: CssExports;
export default cssExports;
