using System;
using System.Collections.Generic;
using NzbDrone.Core.Datastore;
namespace NzbDrone.Core.MediaFiles.RecoverableOperations
{
    public enum RecoverableOperationType { Delete = 1, Import = 2, Rename = 3, Move = 4, Promote = 5 }
    public enum RecoverableOperationState { Pending = 1, Staging = 2, Staged = 3, ApplyingDatabase = 4, DatabaseCommitted = 5, Finalizing = 6, Completed = 7, RollingBack = 8, RolledBack = 9, RecoveryRequired = 10 }
    public enum RecoverableTransferMode { None = 0, Move = 1, Copy = 2, HardLink = 3, Reflink = 4 }
    [Flags] public enum RecoverableOperationEventDispatchMask : long { None = 0 }
    public sealed class RecoverableOperationSnapshot { public int MovieId { get; init; } public int? MovieFileId { get; init; } public int? MovieEditionSlotId { get; init; } public string Path { get; init; } public string DestinationPath { get; init; } public long? Size { get; init; } }
    public sealed class RecoverableOperationPlan : IEmbeddedDocument { public RecoverableOperationSnapshot Expected { get; init; } public RecoverableOperationSnapshot Desired { get; init; } public string SourcePath { get; init; } public string StagingPath { get; init; } public string DestinationPath { get; init; } public string FinalizePath { get; init; } public long? ExpectedSize { get; init; } public RecoverableTransferMode TransferMode { get; init; } public Dictionary<string, string> EventFacts { get; init; } = new(); }
    public sealed class RecoverableOperation : ModelBase { public string OperationKey { get; set; } public string ResourceKey { get; set; } public string ActiveResourceKey { get; set; } public RecoverableOperationType OperationType { get; set; } public RecoverableOperationState State { get; set; } public int MovieId { get; set; } public int? MovieFileId { get; set; } public int? MovieEditionSlotId { get; set; } public RecoverableOperationPlan Plan { get; set; } public string StagingRoot { get; set; } public int Version { get; set; } public int AttemptCount { get; set; } public DateTime? LastAttemptAt { get; set; } public string LastError { get; set; } public string LeaseOwner { get; set; } public DateTime? LeaseExpiresAt { get; set; } public DateTime CreatedAt { get; set; } public DateTime UpdatedAt { get; set; } public DateTime? DatabaseCommittedAt { get; set; } public DateTime? CompletedAt { get; set; } public long EventDispatchMask { get; set; } }
    public sealed class RecoverableOperationCreateRequest { public string OperationKey { get; init; } public string ResourceKey { get; init; } public RecoverableOperationType OperationType { get; init; } public int MovieId { get; init; } public int? MovieFileId { get; init; } public int? MovieEditionSlotId { get; init; } public RecoverableOperationPlan Plan { get; init; } public string StagingRoot { get; init; } }
    public class RecoverableOperationException : Exception { public RecoverableOperationException(string message) : base(message) { } }
    public sealed class RecoverableOperationValidationException : RecoverableOperationException { public RecoverableOperationValidationException(string message) : base(message) { } }
    public sealed class RecoverableOperationResourceConflictException : RecoverableOperationException { public RecoverableOperationResourceConflictException(string resource) : base($"An active recoverable operation already owns resource '{resource}'.") { } }
    public sealed class RecoverableOperationTransitionException : RecoverableOperationException { public RecoverableOperationTransitionException(RecoverableOperationState from, RecoverableOperationState to) : base($"Recoverable operation transition from {from} to {to} is not legal.") { } }
    public sealed class RecoverableOperationConcurrencyException : RecoverableOperationException { public RecoverableOperationConcurrencyException(int id) : base($"Recoverable operation {id} changed or its lease is unavailable.") { } }
}
